import { useState, useEffect, useCallback, useRef } from "react";
import { motion, AnimatePresence, PanInfo } from "framer-motion";
import {
  WorkoutStats,
  ClassmateStats,
  LocationStats,
  PeerStats,
} from "../types/stats";
import "./SlideShow.css";
import { Pie } from "react-chartjs-2";
import { Chart as ChartJS, ArcElement, Tooltip, Legend } from "chart.js";
import Confetti from "react-confetti";

ChartJS.register(ArcElement, Tooltip, Legend);

// Instagram handle lookup by location name
// Auto-generated by scrape-instagram-handles.ts
// Format: { handle: "@handle", url: "https://www.instagram.com/handle" }
const LOCATION_INSTAGRAM: Record<string, { handle: string; url: string }> = {
  "MADabolic Santa Clara": {
    handle: "@madabolic_santaclara",
    url: "https://www.instagram.com/madabolic_santaclara",
  },
  "MADabolic Scotts Valley": {
    handle: "@mad_scottsvalley",
    url: "https://www.instagram.com/mad_scottsvalley",
  },
  "MADabolic RiNo": {
    handle: "@madabolic_rino",
    url: "https://www.instagram.com/madabolic_rino",
  },
  "MADabolic Westminster": {
    handle: "@mad_westminster",
    url: "https://www.instagram.com/mad_westminster",
  },
  "MADabolic Stamford": {
    handle: "@mad_stamford",
    url: "https://www.instagram.com/mad_stamford",
  },
  "MADabolic Jupiter": {
    handle: "@mad_jupiterfl",
    url: "https://www.instagram.com/mad_jupiterfl",
  },
  "MADabolic Oakland Park": {
    handle: "@mad_oaklandpark",
    url: "https://www.instagram.com/mad_oaklandpark",
  },
  "MADabolic Ybor City": {
    handle: "@mad_yborcity",
    url: "https://www.instagram.com/mad_yborcity",
  },
  "MADabolic Atlanta": {
    handle: "@mad_atlanta",
    url: "https://www.instagram.com/mad_atlanta",
  },
  "MADabolic Broad Ripple": {
    handle: "@mad_broadripple",
    url: "https://www.instagram.com/mad_broadripple",
  },
  "MADabolic ICT East": {
    handle: "@mad_icteast",
    url: "https://www.instagram.com/mad_icteast",
  },
  "MADabolic Lexington": {
    handle: "@mad_lexington",
    url: "https://www.instagram.com/mad_lexington",
  },
  "MADabolic Brooklyn": {
    handle: "@madabolic_brooklyn",
    url: "https://www.instagram.com/madabolic_brooklyn",
  },
  "MADabolic Asheville": {
    handle: "@madasheville",
    url: "https://www.instagram.com/madasheville",
  },
  "MADabolic Elizabeth": {
    handle: "@madclt",
    url: "https://www.instagram.com/madclt",
  },
  "MADabolic NoDa": {
    handle: "@madclt",
    url: "https://www.instagram.com/madclt",
  },
  "MADabolic South End": {
    handle: "@madclt",
    url: "https://www.instagram.com/madclt",
  },
  "MADabolic North Raleigh": {
    handle: "@mad_northraleigh",
    url: "https://www.instagram.com/mad_northraleigh",
  },
  "MADabolic Raleigh": {
    handle: "@madraleigh",
    url: "https://www.instagram.com/madraleigh",
  },
  "MADabolic Cincinnati": {
    handle: "@mad_cincy",
    url: "https://www.instagram.com/mad_cincy",
  },
  "MADabolic OKC": {
    handle: "@mad_okc",
    url: "https://www.instagram.com/mad_okc",
  },
  "MADabolic Bend": {
    handle: "@madabolic",
    url: "https://www.instagram.com/madabolic",
  },
  "MADabolic Fishtown": {
    handle: "@madabolic",
    url: "https://www.instagram.com/madabolic",
  },
  "MADabolic North Hills": {
    handle: "@mad_northhills",
    url: "https://www.instagram.com/mad_northhills",
  },
  "MADabolic Strip District": {
    handle: "@mad_thestrip",
    url: "https://www.instagram.com/mad_thestrip",
  },
  "MADabolic Greenville": {
    handle: "@madgreenville",
    url: "https://www.instagram.com/madgreenville",
  },
  "MADabolic Nashville": {
    handle: "@mad_nashville",
    url: "https://www.instagram.com/mad_nashville",
  },
  "MADabolic Austin North": {
    handle: "@madaustintx",
    url: "https://www.instagram.com/madaustintx",
  },
  "MADabolic Austin South": {
    handle: "@madaustintx",
    url: "https://www.instagram.com/madaustintx",
  },
  "MADabolic Bishop Arts": {
    handle: "@madabolic",
    url: "https://www.instagram.com/madabolic",
  },
  "MADabolic Ion District": {
    handle: "@mad_iondistrict",
    url: "https://www.instagram.com/mad_iondistrict",
  },
  "MADabolic La Cantera Heights": {
    handle: "@mad_lacantera",
    url: "https://www.instagram.com/mad_lacantera",
  },
  "MADabolic McAllen": {
    handle: "@mad_mcallen",
    url: "https://www.instagram.com/mad_mcallen",
  },
  "MADabolic Southlake": {
    handle: "@mad_southlake",
    url: "https://www.instagram.com/mad_southlake",
  },
  "MADabolic The Heights": {
    handle: "@mad_theheights",
    url: "https://www.instagram.com/mad_theheights",
  },
  "MADabolic West Plano": {
    handle: "@mad_westplano",
    url: "https://www.instagram.com/mad_westplano",
  },
  "MADabolic Alexandria": {
    handle: "@mad_dmv",
    url: "https://www.instagram.com/mad_dmv",
  },
  "MADabolic Arlington": {
    handle: "@mad_dmv",
    url: "https://www.instagram.com/mad_dmv",
  },
  "MADabolic Charlottesville": {
    handle: "@mad_charlottesville",
    url: "https://www.instagram.com/mad_charlottesville",
  },
  "MADabolic Winchester": {
    handle: "@madabolic_winchester",
    url: "https://www.instagram.com/madabolic_winchester",
  },
  "MADabolic 14th street": {
    handle: "@mad_dmv",
    url: "https://www.instagram.com/mad_dmv",
  },
  "MADabolic Dupont": {
    handle: "@mad_dmv",
    url: "https://www.instagram.com/mad_dmv",
  },
  "MADabolic H Street": {
    handle: "@mad_dmv",
    url: "https://www.instagram.com/mad_dmv",
  },
  "MADabolic Madison": {
    handle: "@madabolic_madison",
    url: "https://www.instagram.com/madabolic_madison",
  },
  // Locations not on main site but in scraper
  "MADabolic Commack": {
    handle: "@madabolic",
    url: "https://www.instagram.com/madabolic",
  },
  "MADabolic St. Pete": {
    handle: "@madabolic",
    url: "https://www.instagram.com/madabolic",
  },
};

// Default fallback Instagram info
const DEFAULT_INSTAGRAM = {
  handle: "@madabolic",
  url: "https://www.instagram.com/madabolic",
};

// Normalize location name: lowercase and remove non-alphanumeric characters
const normalizeLocationName = (name: string) =>
  name.toLowerCase().replace(/[^a-z0-9]/g, "");

// Create a normalized lookup map for fuzzy matching
const LOCATION_INSTAGRAM_NORMALIZED = Object.fromEntries(
  Object.entries(LOCATION_INSTAGRAM).map(([key, value]) => [
    normalizeLocationName(key),
    value,
  ])
);

// Helper to get Instagram info for a location (case-insensitive, ignores spaces/punctuation)
const getLocationInstagram = (locationName: string) => {
  const insta =
    LOCATION_INSTAGRAM_NORMALIZED[normalizeLocationName(locationName)];
  if (insta && insta.handle) {
    return insta;
  }
  return DEFAULT_INSTAGRAM;
};

interface SlideShowProps {
  stats: WorkoutStats;
  peerStats?: PeerStats;
  studioId: string;
}

const SlideShow = ({ stats, studioId }: SlideShowProps) => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [dragDirection, setDragDirection] = useState<number>(0);
  const slideRef = useRef<HTMLDivElement>(null);
  const swipeConfidenceThreshold = 50;

  // Track slide view in GA4
  const trackSlideView = useCallback(
    (slideId: string) => {
      window.gtag?.("event", "page_view", {
        page_title: `MAD Wrapped - ${slideId}`,
        page_path: `/wrapped/${slideId}`,
        client_id: stats.clientId,
        studio_id: studioId,
        unique_id: `${stats.clientId}-${studioId}`,
      });
    },
    [stats.clientId, studioId]
  );

  const paginate = (direction: number) => {
    setCurrentSlide((prev) => {
      const nextSlide = prev + direction;
      if (nextSlide < 0) return slides.length - 1;
      if (nextSlide >= slides.length) return 0;
      return nextSlide;
    });
  };

  // Track slide changes
  useEffect(() => {
    if (slides[currentSlide]) {
      trackSlideView(slides[currentSlide].id);
    }
  }, [currentSlide, trackSlideView]);

  const handleKeyDown = useCallback((event: KeyboardEvent) => {
    if (event.key === "ArrowLeft") {
      paginate(-1);
    } else if (event.key === "ArrowRight") {
      paginate(1);
    }
  }, []);

  useEffect(() => {
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [handleKeyDown]);

  const handleDragEnd = (
    _event: MouseEvent | TouchEvent | PointerEvent,
    info: PanInfo
  ) => {
    if (info.offset.x < -swipeConfidenceThreshold) {
      paginate(1);
    } else if (info.offset.x > swipeConfidenceThreshold) {
      paginate(-1);
    }
  };

  const handleDrag = (
    _event: MouseEvent | TouchEvent | PointerEvent,
    info: PanInfo
  ) => {
    setDragDirection(info.offset.x > 0 ? -1 : 1);
  };

  const slides = [
    {
      id: "total-classes",
      content: (
        <>
          <h2>Your Year in Review</h2>
          <div className="stat-number">{stats.totalClasses}</div>
          <p>Total classes crushed in 2025</p>
          {stats.allTimeClasses > stats.totalClasses && (
            <p className="all-time-subtext">
              {stats.allTimeClasses} all-time classes since you joined
            </p>
          )}
        </>
      ),
    },
    {
      id: "member-comparison",
      content: (
        <>
          <h2>How You Stack Up</h2>
          <div className="percentile-grid">
            <div className="percentile-item">
              <div className="percentile-label">Total Classes</div>
              <div className="percentile-value">
                {100 - stats.peerComparison.percentiles.totalClasses <= 1
                  ? "Top 1% 🏆"
                  : `Top ${
                      100 - stats.peerComparison.percentiles.totalClasses
                    }%`}
              </div>
              <div className="percentile-context">Of all members</div>
            </div>
            <div className="percentile-item">
              <div className="percentile-label">Perfect Weeks</div>
              <div className="percentile-value">
                {100 - stats.peerComparison.percentiles.perfectWeeks <= 1
                  ? "Top 1% 🏆"
                  : `Top ${
                      100 - stats.peerComparison.percentiles.perfectWeeks
                    }%`}
              </div>
              <div className="percentile-context">In perfect weeks</div>
            </div>
            <div className="percentile-item">
              <div className="percentile-label">Early Bird Status</div>
              <div className="percentile-value">
                {100 - stats.peerComparison.percentiles.earlyBirdScore <= 1
                  ? "Top 1% 🏆"
                  : `Top ${
                      100 - stats.peerComparison.percentiles.earlyBirdScore
                    }%`}
              </div>
              <div className="percentile-context">Of early risers</div>
            </div>
          </div>
        </>
      ),
    },
    ...(stats.classesByYear?.length > 1
      ? [
          {
            id: "yearly-trend",
            content: (
              <>
                <h2>Your MAD Journey</h2>
                <div
                  className={`yearly-chart ${
                    stats.classesByYear.length >= 7 ? "many-years" : ""
                  }`}
                >
                  {stats.classesByYear.map((yearData, index) => {
                    const maxCount = Math.max(
                      ...stats.classesByYear.map((y) => y.count)
                    );
                    const heightPercent = (yearData.count / maxCount) * 100;
                    return (
                      <div key={yearData.year} className="year-bar">
                        <motion.div
                          className="year-bar-fill"
                          initial={{ height: 0 }}
                          animate={{ height: `${heightPercent}%` }}
                          transition={{ delay: index * 0.15, duration: 0.5 }}
                        >
                          <span className="year-bar-count">
                            {yearData.count}
                          </span>
                        </motion.div>
                        <span
                          className={`year-label ${
                            yearData.year === 2025 ? "current-year" : ""
                          }`}
                        >
                          {yearData.year}
                        </span>
                      </div>
                    );
                  })}
                </div>
                <p>
                  {stats.classesByYear.length} years of crushing it at
                  MADabolic!
                </p>
              </>
            ),
          },
        ]
      : []),
    {
      id: "monthly-progress",
      content: (
        <>
          <h2>Your Year at MAD</h2>
          <div className="monthly-chart">
            {stats.classesPerMonth.map((month, index) => (
              <div key={month.month} className="month-bar">
                <motion.div
                  className="bar"
                  initial={{ height: 0 }}
                  animate={{ height: `${(month.count / 20) * 100}%` }}
                  transition={{ delay: index * 0.1 }}
                />
                <span className="month-label">{month.month}</span>
                <span className="count-label">{month.count}</span>
              </div>
            ))}
          </div>
        </>
      ),
    },
    {
      id: "class-types",
      content: (
        <>
          <h2>Your MAD Mix</h2>
          <div className="pie-chart-container">
            <Pie
              data={{
                labels: ["Durability", "Anaerobic", "Momentum"],
                datasets: [
                  {
                    data: [
                      stats.durabilityClasses,
                      stats.anaerobicClasses,
                      stats.momentumClasses,
                    ],
                    backgroundColor: ["#06C7A6", "#616161", "#ffffff"],
                    borderColor: [
                      "rgba(0, 0, 0, 0.4)",
                      "rgba(0, 0, 0, 0.2)",
                      "rgba(0, 0, 0, 0.2)",
                    ],
                    borderWidth: 1,
                  },
                ],
              }}
              options={{
                plugins: {
                  legend: {
                    display: false,
                  },
                  tooltip: {
                    enabled: true,
                    backgroundColor: "rgba(0, 0, 0, 0.8)",
                    titleColor: "#fff",
                    bodyColor: "#fff",
                    padding: 12,
                    displayColors: false,
                    callbacks: {
                      label: function (context) {
                        const total = context.dataset.data.reduce(
                          (a: number, b: number) => a + b,
                          0
                        );
                        const value = context.raw as number;
                        const percentage = ((value / total) * 100).toFixed(1);
                        return `${value} classes (${percentage}%)`;
                      },
                    },
                  },
                },
                responsive: true,
                maintainAspectRatio: true,
                layout: {
                  padding: {
                    top: 10,
                    bottom: 10,
                  },
                },
              }}
            />
          </div>
          <p className="stat-detail">
            You crushed <br />
            <span className="momentum-text">
              {stats.momentumClasses} Momentum
            </span>{" "}
            <span className="anaerobic-text">
              {stats.anaerobicClasses} Anaerobic
            </span>{" "}
            <span className="durability-text">
              {stats.durabilityClasses} Durability
            </span>
            <br />
            {stats.deloadClasses > 0 ? (
              <span>and {stats.deloadClasses} de-load</span>
            ) : null}{" "}
            classes!
          </p>
        </>
      ),
    },
    {
      id: "time-patterns",
      content: (
        <>
          <h2>Your Workout Schedule</h2>
          <div className="time-patterns">
            <div className="pattern-item">
              <span className="highlight">
                {stats.favoriteTimeOfDay.replace(/^0/, "")}
              </span>
              <p>Favorite time</p>
            </div>
            <div className="pattern-item">
              <span className="highlight">{stats.mostFrequentDay}</span>
              <p>Most frequent day</p>
            </div>
            <div className="pattern-item">
              <span className="highlight">{stats.earlyBirdScore}%</span>
              <p>Classes before 8am</p>
            </div>
          </div>
        </>
      ),
    },
    {
      id: "streak",
      content: (
        <>
          <h2>Perfect MAD Weeks</h2>
          <div className="stat-number">{stats.perfectMadWeeks}</div>
          <p>Weeks with 4+ classes</p>
        </>
      ),
    },
    {
      id: "favorite-coach",
      content: (
        <>
          <h2>Your Favorite Coach</h2>
          <div className="stat-text">
            {stats.topCoach
              .split(" ")
              .map((part, index, array) =>
                index === array.length - 1 ? `${part[0]}.` : part
              )
              .join(" ")}
          </div>
          <p>Thanks for the motivation!</p>
        </>
      ),
    },
    {
      id: "workout-buddies",
      content: (
        <>
          <h2>Your Workout Buddies</h2>
          <div className="workout-buddies">
            {stats.peerComparison.topClassmates.map(
              (buddy: ClassmateStats, index: number) => (
                <div key={index} className="buddy-item">
                  <div className="buddy-name">{`${
                    buddy.firstName
                  } ${buddy.lastName.slice(0, 1)}.`}</div>
                  <div className="shared-classes">{buddy.sharedClasses}</div>
                  <p>Classes together</p>
                </div>
              )
            )}
          </div>
        </>
      ),
    },
    {
      id: "favorite-location",
      content: (
        <>
          <h2>Your MAD Home</h2>
          <div className="stat-text">
            {stats.favoriteLocation.name.replace("MADabolic ", "")}
          </div>
          <p>{stats.favoriteLocation.percentage}% of your classes were here</p>
        </>
      ),
    },
    ...(stats.locationBreakdown?.length > 1
      ? [
          {
            id: "other-locations",
            content: (
              <>
                <h2>Your MAD Adventures</h2>
                <div className="other-locations">
                  {stats.locationBreakdown
                    .filter(
                      (location: LocationStats) =>
                        location.name !== stats.favoriteLocation.name
                    )
                    .map((location: LocationStats, index: number) => (
                      <div key={index} className="location-item">
                        <div className="location-name">
                          {location.name
                            .replace("MADabolic - ", "")
                            .replace("MADabolic ", "")
                            .replace("Madabolic ", "")
                            .replace("MAD ", "")}
                        </div>
                        <div className="location-percentage">
                          {location.count}
                        </div>
                        <p>Classes</p>
                        <div className="location-percentage-small">
                          {location.percentage}% of total
                        </div>
                      </div>
                    ))}
                </div>
              </>
            ),
          },
        ]
      : []),
    {
      id: "booking-habits",
      content: (
        <>
          <h2>Booking Habits</h2>
          <div className="booking-stats">
            <div className="booking-item">
              <span className="stat-circle">{stats.totalLateBookings}</span>
              <p>Last-minute bookings</p>
            </div>
            <div className="booking-item">
              <span className="stat-circle">{stats.totalCancellations}</span>
              <p>Cancellations</p>
            </div>
          </div>
        </>
      ),
    },
    {
      id: "final-slide",
      content: (() => {
        const insta = getLocationInstagram(stats.favoriteLocation.name);
        return (
          <>
            <div
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                width: "100%",
                height: "100%",
                overflow: "hidden",
                pointerEvents: "none",
              }}
            >
              <Confetti
                width={600}
                height={600}
                recycle={false}
                numberOfPieces={250}
              />
            </div>
            <h2>Ready to Crush 2026?</h2>
            <div className="share-section">
              <p className="share-text">Share your MAD journey on Instagram!</p>
              <p className="tag-text">
                Tag us{" "}
                <a
                  href={insta.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: "inherit", textDecoration: "none" }}
                >
                  {insta.handle}
                </a>
              </p>
              <div className="motivation-text">
                Let's see how you'll stack up next year! 💪
              </div>
            </div>
          </>
        );
      })(),
    },
  ];

  return (
    <div className="slideshow">
      <div className="slide-header">
        <img src="/mad_logo.svg" alt="MAD Logo" className="mad-logo" />
        <h1 className="year-title">{stats.firstName}'s 2025 Year in Review</h1>
      </div>
      <motion.div
        className="slide-container"
        whileHover={{ scale: 1.02 }}
        transition={{ type: "spring", stiffness: 400, damping: 25 }}
        onClick={() => paginate(1)}
      >
        <AnimatePresence mode="wait">
          <motion.div
            key={currentSlide}
            ref={slideRef}
            className="slide"
            initial={{ opacity: 0, x: 50 * dragDirection }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -50 * dragDirection }}
            transition={{
              type: "spring",
              stiffness: 300,
              damping: 30,
            }}
            drag="x"
            dragConstraints={{ left: 0, right: 0 }}
            dragElastic={0}
            onDrag={handleDrag}
            onDragEnd={handleDragEnd}
            whileTap={{ cursor: "grabbing" }}
          >
            {slides[currentSlide].content}
          </motion.div>
        </AnimatePresence>
      </motion.div>

      <motion.div
        className="progress-dots"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5 }}
      >
        {slides.map((_, index) => (
          <motion.div
            key={index}
            className={`dot ${index === currentSlide ? "active" : ""}`}
            onClick={(e) => {
              e.stopPropagation();
              setCurrentSlide(index);
            }}
            whileHover={{ scale: 1.5 }}
            whileTap={{ scale: 0.9 }}
            animate={
              index === currentSlide
                ? {
                    scale: [1, 1.2, 1],
                    transition: {
                      duration: 0.5,
                      ease: "easeInOut",
                    },
                  }
                : {}
            }
          />
        ))}
      </motion.div>
    </div>
  );
};

export default SlideShow;
